### PR TITLE
Subscan time filtering

### PR DESCRIPTION
**Pull request by karan-batavia**
Subscan times are filtered out from the `privado-core scan` output.

### CODE REVIEW

**Comment by abhstabs** [comment]
Can you give more context on this change? Thanks.

**Comment by ankit-privado** [comment]
@abhstabs This change is related to the capturing the different time present at last when we run privado scan and showing in our final report. 

c.c. @karan-batavia

**Review by abhstabs — COMMENTED** [review]
Are we calling these functions somewhere at the moment?

**Comment by ankit-privado** [comment]
Not sure about this. @karan-batavia can you pls give more context about this?

**Comment by karan-batavia** [comment]
No @abhstabs, we aren't calling these anywhere at the moment.

**Pull request closed without merging**
