### PR TITLE
Fix summary and remove some sections

### PR DESCRIPTION
**Pull request by karan-batavia**
We've removed Scan time, Reachable By Flow time, Reachable by flow count from the slack summary. 
Introduced a DiffCache where the missing nodes are populated at generation time itself.

### CODE REVIEW

**Review by ankit-privado — APPROVED** [review]
LGTM

**Comment by pandurangpatil** [comment]
@karan-batavia did we remove the mentioned summary items ? Can you share the screenshot of the new summary

**Comment by karan-batavia** [comment]
> @karan-batavia did we remove the mentioned summary items ? Can you share the screenshot of the new summary

Yes, @pandurangpatil

**Comment by pandurangpatil** [comment]
@karan-batavia can you add this update over the ticket along with the updated screenshot and create a separate ticket to introduce it again? tag @khemrajrathore @tuxology @dbMundada @hiteshbedre so the team is on the same page.

**Pull request merged**
